### ISSUE TITLE
Cuda out of memory error for another dataset for a 45 Gb GPU

### ISSUE THREAD

**Issue by yaswanth-iitkgp** [GanjinZero/Triaffine-nested-ner#5]
Can you tell anything that i can do to run it successfully ?

File "model5/Triaffine-nested-ner/model/span_att_v2.py", line 405, in get_class_position
    score = contract('bxi,bzrk,ikjr,bxj->bzxr', x3, h_span3, self.parser_list[0].parser1.weight, y3)
  File "anaconda3/envs/model5/lib/python3.7/site-packages/opt_einsum/contract.py", line 507, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "anaconda3/envs/model5/lib/python3.7/site-packages/opt_einsum/contract.py", line 573, in _core_contract
    new_view = _tensordot(*tmp_operands, axes=(tuple(left_pos), tuple(right_pos)), backend=backend)
  File "anaconda3/envs/model5/lib/python3.7/site-packages/opt_einsum/sharing.py", line 131, in cached_tensordot
    return tensordot(x, y, axes, backend=backend)
  File "anaconda3/envs/model5/lib/python3.7/site-packages/opt_einsum/contract.py", line 374, in _tensordot
    return fn(x, y, axes=axes)
  File "anaconda3/envs/model5/lib/python3.7/site-packages/opt_einsum/backends/torch.py", line 54, in tensordot
    return torch.tensordot(x, y, dims=axes)
  File "anaconda3/envs/model5/lib/python3.7/site-packages/torch/functional.py", line 936, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore

RuntimeError: CUDA out of memory. Tried to allocate 10.69 GiB (GPU 0; 44.40 GiB total capacity; 34.47 GiB already allocated; 8.00 GiB free; 35.18 GiB reserved in total by PyTorch)

**Comment by GanjinZero** [comment]
What is your batch size; att_dim; entity type count?
please try batch size=1, lower your att_dim to 192/128/64.
If your entity type is too much (over 50), it is hard to use triaffine based model.

**Comment by yaswanth-iitkgp** [comment]
Thanks a lot for your quick reply, 

I used the same batch size i.e 1. entity type count is 86. I used att_dim = 320 (same as yours).
I'll check reducing it down. Because my entity type count is 86, I cannot use this model at all ?? or is there any other recommendation ?

**Comment by GanjinZero** [comment]
Maybe try att_dim=128/64 and apply fp16/bf16 for training.

**Comment by yaswanth-iitkgp** [comment]
sure I'll try with 128 att_dim, and how to apply fp16/bf16 ?

**Comment by GanjinZero** [comment]
Please refer to this https://pytorch.org/blog/accelerating-training-on-nvidia-gpus-with-pytorch-automatic-mixed-precision

Our code does not implement it

**Comment by yaswanth-iitkgp** [comment]
thanks for that. I am able to train the model with att_dim = 128 (consuming only 13gb) , 192(also requires more than 45gb GPU). I haven't implemented that fp16/bf16 assuming it is only for improving performance of gpu.

My dataset is a low resourse dataset so it doesn't have pos, ltokens, rtokens and relations. 
can I know if it can be a cause for reduction in fscore ?? I still got a decent score of 65

**Comment by GanjinZero** [comment]
Without pos Lorien rtoken will reduce your performance, for ace dateset it will downgrade 1-2 f point approximately.

**Comment by yaswanth-iitkgp** [comment]
Thank you so much for your quick responses and your help. I really appreciate it. I just have 1 last question , does the size of att_dim affect the f1score ?? or is it just for performance of GPU ?

**Comment by GanjinZero** [comment]
I think it does effect F1, while we do not experiment it.

**Comment by yaswanth-iitkgp** [comment]
ok thank you very much for you informative answers and help
